Api
kvvPro/gophermart pull request #1
Opened 2023-08-19 14:23 UTC by kvvPro

2023-08-25 18:19 UTC, valentinsoe requested changes
Спасибо за работу!
Комментарии написал по ходу PR

Что еще стоит улучшить:
1) Разделение кода на файлы(модули). Сейчас все очень крупными блоками.
2) Нет тестов
3) Безопасность. Нигде не проверяется пароль. Он хранится в БД и даже в JWT токене в открытом виде
4) Производительность. При текущем подходе пропускная способность обращений к внешнему сервису очень низкая. Стоит распараллелить его вызовы.
5) Бизнес-логика почти вся на уровне хранилища. Хотя ей бы стоило быть в слове бизнес-логики(app)

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/auth/auth.go
> +// и одно пользовательское — UserID
Комментарий и содержимое структуры отличаются

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/auth/auth.go
> +	UserPass  string
Передавать пароль в JWT токене - небезопасно. 
К тому же в этом нет необходимости

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/compress.go
Я бы этот файл перенес в internal. Он достаточно универсалени не относится к инициализации приложения.

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/app.go
> +		retry.InitDelay(1000*time.Millisecond),
Занудство(исправлять не требуется). Но это очень большие задержки для работы с БД.

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/app.go
> +func (srv *Server) CheckUser(ctx context.Context, user *model.User) (*model.User, error) {
Занудство. Функция называется Check, а делает Get.

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/app.go
> +func (srv *Server) GetCurrentBalance(ctx context.Context, userInfo *model.User) (*model.Balance, error) {
Опять мелкое занудство.
GetCurrentBalance вызывает GetBalance. В какой-то момент он баланс становится не текущим, а просто балансом. Предлагаю убрать Current, потому что никакого другого баланса у нас нет

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/app.go
> +func (srv *Server) RequestWithdraw(ctx context.Context, withdrawalInfo *model.Withdrawal) (model.EndPointStatus, error) {
И тут мелкое занудство. Request Withdraw - два глагола подряд:) А вот в сторадже функция называется корректно.

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/app.go
> +					continue
Ошибки лучше хотя бы залогировать.
continue тут лишний, это итак последняя операция .

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/app.go
> +		localURL := strings.Replace(url, "{number}", el.ID, 1)
Рекомендую использовать форматирование строки, а не замену.
Это и выглядит аккуратнее и выполняется быстрее.

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/app.go
> +		response.Body.Close()
Мы может выйти из итерации цикла не закрыв response.Body.

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/app.go
Очень большой файл, который делает всё.
Инициализирует роутер, ходит во внешний сервис, оборачивает вызовы хранилища.
Предлагаю разделить его на отдельные файлы(а лучше модули).

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/handlers.go
> +var ContentTypesForCompress = "application/json; text/html"
Кажется эту константу лучше унести либо в compress, либо  туда, где compress инициализируется.

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/handlers.go
> +func WithLogging(h http.Handler) http.Handler {
Лучше убрать в отдельный файл с middleware.

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/handlers.go
> +	err = srv.AddUser(context.Background(), &user)
Не стоит создавать новый Background контекст, у нас есть контекст запроса, стоит передавать его.

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/handlers.go
> +			http.Error(w, "логин уже занят: "+err.Error(), http.StatusConflict)
Лучше ошибку записать в лог. Врядли она внешнему пользователю будет полезна.

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/app/handlers.go
> +	userInfo, err := srv.CheckUser(context.Background(), &user)
Где-то здесь должна быть проверка пароля пользователя.

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/config/flags.go
> +	fmt.Println("\nFLAGS-----------")
Если в проекте есть логгер, лучше использовать его.
Если он станет настроен не на stdout, то такие сообщения будут утеряны.

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/main.go
> +	sigQuit := <-shutdown
После получения сигнала стоит остановить сервис и "асинхронный обновлятор".

2023-08-25 18:19 UTC, valentinsoe commented on cmd/gophermart/main.go
> +	srv, err := app.NewServer(context.Background(), &srvFlags)
Мы создаем 3 разных бекграунд контекста. Хотя могли бы обойтись одним..

2023-08-25 18:19 UTC, valentinsoe commented on internal/luhn/luhn.go
> +func Generate(length int) string {
Кажется нам функции генерации не нужны.

2023-08-25 18:19 UTC, valentinsoe commented on internal/retry/options.go
Рекомендовал бы подключить как внешний пакет(если нет существенных модификаций в коде)

2023-08-25 18:19 UTC, valentinsoe commented on internal/storage/postgres/postgres.go
> +	transaction, err := s.pool.Begin(ctx)
Нет необходимости создавать транзакцию для одной операции. Она итак выполнится в рамках транзакции.

2023-08-25 18:19 UTC, valentinsoe commented on internal/storage/postgres/postgres.go
> +	switch err := result.Scan(&allBonuses, &allWithdrawals); err {
А вот здесь как раз нам пригодится транзакция. Потому что баланс между этим вызовом и вызовом на создание списания может изменится.

2023-08-25 19:29 UTC, kvvPro commented on cmd/gophermart/auth/auth.go
> +// и одно пользовательское — UserID
Поправил

2023-08-25 19:29 UTC, kvvPro commented on cmd/gophermart/auth/auth.go
> +	UserPass  string
Поправил

2023-08-25 19:32 UTC, kvvPro commented on cmd/gophermart/app/compress.go
исправил

2023-08-25 19:35 UTC, kvvPro commented on cmd/gophermart/app/app.go
> +		retry.InitDelay(1000*time.Millisecond),
поправил

2023-08-25 19:36 UTC, kvvPro commented on cmd/gophermart/app/app.go
> +func (srv *Server) CheckUser(ctx context.Context, user *model.User) (*model.User, error) {
поправил

2023-08-25 19:38 UTC, kvvPro commented on cmd/gophermart/app/app.go
> +func (srv *Server) GetCurrentBalance(ctx context.Context, userInfo *model.User) (*model.Balance, error) {
поправил

2023-08-25 19:39 UTC, kvvPro commented on cmd/gophermart/app/app.go
> +func (srv *Server) RequestWithdraw(ctx context.Context, withdrawalInfo *model.Withdrawal) (model.EndPointStatus, error) {
поправил

2023-08-25 19:41 UTC, kvvPro commented on cmd/gophermart/app/app.go
> +					continue
поправил

2023-08-25 19:49 UTC, kvvPro commented on cmd/gophermart/app/app.go
> +		localURL := strings.Replace(url, "{number}", el.ID, 1)
поправил

2023-08-25 19:50 UTC, kvvPro commented on cmd/gophermart/app/app.go
> +		response.Body.Close()
поправил

2023-08-25 19:54 UTC, kvvPro commented on cmd/gophermart/app/handlers.go
> +var ContentTypesForCompress = "application/json; text/html"
поправил

2023-08-25 20:00 UTC, kvvPro commented on cmd/gophermart/app/handlers.go
> +func WithLogging(h http.Handler) http.Handler {
вынес

2023-08-25 20:02 UTC, kvvPro commented on cmd/gophermart/app/handlers.go
> +	err = srv.AddUser(context.Background(), &user)
поправил во всех хендлерах

2023-08-26 11:12 UTC, kvvPro commented on cmd/gophermart/app/handlers.go
> +			http.Error(w, "логин уже занят: "+err.Error(), http.StatusConflict)
добавил и в другие места

2023-08-26 11:35 UTC, kvvPro commented on cmd/gophermart/app/handlers.go
> +	userInfo, err := srv.CheckUser(context.Background(), &user)
добавил

2023-08-26 11:46 UTC, kvvPro commented on cmd/gophermart/config/flags.go
> +	fmt.Println("\nFLAGS-----------")
поправил

2023-08-26 11:49 UTC, kvvPro commented on cmd/gophermart/main.go
> +	srv, err := app.NewServer(context.Background(), &srvFlags)
поправил

2023-08-26 11:50 UTC, kvvPro commented on internal/luhn/luhn.go
> +func Generate(length int) string {
убрал

2023-08-26 11:52 UTC, kvvPro commented on internal/retry/options.go
еще в лабах были проблемы с подключением, эту библиотеку так и не смог подключить как внешнюю (подключалась более старая версия библиотеки)

2023-08-26 11:53 UTC, kvvPro commented on internal/storage/postgres/postgres.go
> +	transaction, err := s.pool.Begin(ctx)
убрал

2023-08-26 11:57 UTC, kvvPro commented on internal/storage/postgres/postgres.go
> +	switch err := result.Scan(&allBonuses, &allWithdrawals); err {
добавил

2023-08-26 11:58 UTC, kvvPro commented on cmd/gophermart/app/app.go
вынес в отдельные файлы. На модули не совсем понятно зачем делить, т.к. логика всегда привязана к экземпляру сервиса

2023-08-27 19:57 UTC, kvvPro commented on cmd/gophermart/main.go
> +	sigQuit := <-shutdown
добавил завершение и распареллелил обращение к внешней системе

2023-09-05 22:02 UTC, kvvPro commented
Комплексные тесты добавлены в файл app_test.go

2023-09-07 04:42 UTC, valentinsoe commented on internal/retry/options.go
А более старой версии не хватало?

2023-09-07 05:06 UTC, valentinsoe requested changes
Спасибо за исправления!
Что нужно исправить для приема работы:
Многопоточное получение статусов заказа во внешней системе. Сейчас параллелизм реализован в достаточно странном месте. Мы N горутинами получаем одни и те же заказы и обрабатываем их однопоточно.
Вместо экономии ресурсов - получаем наоборот избыточную нагрузку.

Желательно(с учетом времени не думаю, что получится исправить):
Лучше структурировать проект(разделить на хендлеры/бизнес-логику/работу с БД).
Отделить клиента внешнего сервиса от логики работы с ним
Не хранить пароль в открытом виде.
Написать тесты

2023-09-07 05:06 UTC, valentinsoe commented on cmd/gophermart/app/accrual.go
> +			// надо подождать и попробовать заново через Retry-After
Заголовок Retry-After стоит прочитать и использовать его значение

2023-09-07 05:06 UTC, valentinsoe commented on cmd/gophermart/app/app.go
Затем чтобы их:
1) проще было читать
2) можно было отделять друг от друга

2023-09-07 05:06 UTC, valentinsoe commented on cmd/gophermart/app/accrual.go
> +func (srv *Server) RequestAccrual(ctx context.Context, orders []*model.Order) ([]*model.Order, error) {
Нет необходимости передавать по указателю модели(в обоих направлениях)

2023-09-07 05:06 UTC, valentinsoe commented on cmd/gophermart/main.go
> +		go srv.AsyncUpdate(asyncCtx, wg)
Это не лучшее место для параллелизма. Нет нужды многопоточно читать из базы новые заказы. Вычитывать их вполне может одна горутина. А вот обрабатывать стоит многопоточно.

2023-09-07 05:06 UTC, valentinsoe commented on cmd/gophermart/main.go
> +		go srv.AsyncUpdate(asyncCtx, wg)
При такой реализации будет много потоков постоянно долбящих внешний сервис по одному и тому же заказу.

2023-09-07 05:06 UTC, valentinsoe commented on cmd/gophermart/app/handlers.go
> +	token, err := auth.BuildJWTString(user.Login, user.Password)
password нам не нужен для генерации токена

2023-09-07 16:02 UTC, kvvPro commented on cmd/gophermart/app/handlers.go
> +	token, err := auth.BuildJWTString(user.Login, user.Password)
поправил

2023-09-07 16:02 UTC, kvvPro commented on cmd/gophermart/main.go
> +		go srv.AsyncUpdate(asyncCtx, wg)
вынес в горутины именно апдейт заказов в БД

2023-09-07 16:02 UTC, kvvPro commented on cmd/gophermart/app/accrual.go
> +func (srv *Server) RequestAccrual(ctx context.Context, orders []*model.Order) ([]*model.Order, error) {
поправил

2023-09-08 04:08 UTC, valentinsoe requested changes
Спасибо за исправления, но пока не все исправлено.

Написал ряд замечаний - критичное это то, что мы выполняем многопоточно не ту операцию:)

2023-09-08 04:08 UTC, valentinsoe commented on cmd/gophermart/app/app.go
> +				batchSize := length / srv.UpdateThreadCount
С точки зрения идиоматического Go - это очень сложное колдунство:)
Можно просто запустить N горутин читающих из канала, и писать в него задания

2023-09-08 04:08 UTC, valentinsoe commented on cmd/gophermart/app/app.go
> +						_ = srv.UpdateOrders(ctx, wg, batchForUpdate)
При одном заказе и 10 потоках - мы запустим 9 горутин передав им пустой слайс:)

2023-09-08 04:08 UTC, valentinsoe commented on cmd/gophermart/app/app.go
> +			ordersForUpdate, _ := srv.RequestAccrual(ctx, orders)
Вот эта функция должна выполняться многопоточно. А не обновление записей в БД:)
Обычно до БД у нас не такая большая latency, в отличие от внешних http-сервисов

2023-09-08 04:08 UTC, valentinsoe commented on cmd/gophermart/app/orders.go
> +func (srv *Server) UpdateOrders(ctx context.Context, wg *sync.WaitGroup, orders []model.Order) error {
Такой подход не позволяет выполнить функцию без передачи в нее ворк-группы.
Лучше так не делать, а вызывать в анонимной функции.
 go func() {
  defer wg.Done()
 srv.UpdateOrders(....)
   }

2023-09-08 04:08 UTC, valentinsoe commented on cmd/gophermart/app/app.go
> +				batchSize := length / srv.UpdateThreadCount
Горутина набравшая N записей для сохранения(или канал закрылся) - вызывает сохранение.
Но это не та часть, которую критично паралелить.

2023-09-08 14:48 UTC, kvvPro commented on cmd/gophermart/app/app.go
> +			ordersForUpdate, _ := srv.RequestAccrual(ctx, orders)
я правильно понимаю, что надо сначала сделать функцию для запроса инфы по одному заказу (у меня сейчас цикл), и далее ее пускать в несколько горутин?

2023-09-15 04:40 UTC, valentinsoe approved these changes
Спасибо за исправления!

2023-09-15 06:54 UTC, merged